apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: mybig-team
  description: Does some big stuffs
spec:
  type: team
  profile:
    displayName: My Big Team
    email: test@test.com
  children: []
  members:
    - ckiddy # C Kiddy
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ckiddy
spec:
  profile:
    displayName: C Kiddy
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [mybig-team]
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: bigC
  description: bigC is so big
  links:
    - url: https://github.com/ckiddy
      title: My API dashboard
      icon: dashboard
  annotations:
    github.com/bigC-docs-folder: docs
    github.com/bigC-docs-branch: develop
    backstage.io/source-location: url:https://github.com/ckiddy/my-test
    jenkins.io/job-full-name: folder-name/job-name
    backstage.io/code-coverage: scm-only
    backstage.io/techdocs-ref: dir:.
spec:
  owner: mybig-team
  domain: technology
  dependsOn: 
    - API:auth-api
    - API:config-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mybig_Component
  links:
    - url: https://github.com/ckiddy
      title: My API dashboard
      icon: dashboard
  annotations:
    github.com/project-slug: ckiddy/my-test
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: production
  system: bigC
  owner: mybig-team
  subcomponentOf: anybig-svc
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: anybig-svc
  links:
    - url: https://github.com/ckiddy
      title: My API dashboard
      icon: dashboard
  annotations:
    github.com/project-slug: ckiddy/my-test
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  system: bigC
  owner: mybig-team
  dependsOn:
    - API:auth-api
    - API:config-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: Auth api
  links:
    - url: https://github.com/ckiddy
      title: My API dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: production
  owner: team-x
  definition: |
    openapi: 3.0.0
    info:
      title: Sample API
      description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
      version: 0.1.9
    servers:
      - url: http://api.example.com/v1
        description: Optional server description, e.g. Main (production) server
      - url: http://staging-api.example.com
        description: Optional server description, e.g. Internal staging server for testing
    paths:
      /users:
        get:
          summary: Returns a list of users.
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: config-api
  description: Config api
  links:
    - url: https://github.com/ckiddy
      title: My API dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: production
  owner: mybig-team
  system: bigc
  definition: |
    openapi: 3.0.0
    info:
      title: Sample API
      description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
      version: 0.1.9
    servers:
      - url: http://api.example.com/v1
        description: Optional server description, e.g. Main (production) server
      - url: http://staging-api.example.com
        description: Optional server description, e.g. Internal staging server for testing
    paths:
      /users:
        get:
          summary: Returns a list of users.
          description: Optional extended description in CommonMark or HTML.
          responses:
            '200':    # status code
              description: A JSON array of user names
              content:
                application/json:
                  schema: 
                    type: array
                    items: 
                      type: string
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bigC-common-resource
  description: Stores common constants
spec:
  type: constant
  owner: mybig-team
  system: bigC
  dependencyOf: 
    - API:config-api
